### ISSUE TITLE
Version specifier

### ISSUE THREAD

**Issue by davekaro** [jasonmit/ember-cli-moment-shim#1]
How can I update to moment 2.9? Could whatever is using the shim specify the version? Right now it looks like https://github.com/jasonmit/ember-cli-moment-shim/blob/master/bower.json#L19 is where the version is specified. Maybe loosen that `~2`?

**Comment by jasonmit** [comment]
Ok will loosen the versioning today and release.

As a temp. fix, you could add momentjs in your bower.json along with a resolution pointing to the version you want.

This would override the shims bower.json version of moment

—

**Comment by davekaro** [comment]
Thanks, doing the resolution override makes sense.

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-cli-moment-shim/blob/master/bower.json
