### ISSUE TITLE
[Feature request] support for locales

### ISSUE THREAD

**Issue by nickschot** [jasonmit/ember-cli-moment-shim#11]
It seems there is no option (yet) to easily import/use the locales which come with moment with this shim without adding them to the brocfile/ember-cli-build.

**Comment by jasonmit** [comment]
:+1:

**Comment by jasonmit** [comment]
I'll work on including this.  Are you expecting cherry picked locales to appear in your vendor.js or were you expecting them to just appear in your asset directory to be included via script tags?

**Comment by nickschot** [comment]
I think I'd expect them in the vendor.js at first. Still thinking about the best way to load them as you'll mostly wan't them on the fly depending on browser locale. All locales together are quite hefty at 131kB minified.. so cherry picked would be good.

**Comment by jasonmit** [comment]
Yeah. It's a challenging issue.  Love me some fast boot hooks to inject head content into the DOM so you can conditionally include based on user/request context.

**Comment by jasonmit** [comment]
For now will have them go into vendor.  Thanks for the request, should have something tonight.

**Comment by nickschot** [comment]
Would be interesting to have such possibilities with fastboot indeed. We'll see what the future brings! Thanks for the quick response!

**Comment by jasonmit** [comment]
0.4.0 now features this.  Thanks

**Comment by nickschot** [comment]
:thumbsup:
