### ISSUE TITLE
Tag 0.5.0 release, otherwise bower can't find it.

### ISSUE THREAD

**Issue by abuiles** [jasonmit/ember-cli-moment-shim#14]

**Comment by jasonmit** [comment]
This is now an ember-addon and should be installed through npm.

**Comment by abuiles** [comment]
I got confused because the installer was adding this to my bower.

Anyways, I'm trying to use moment `2.10.5` seems like adding it to the package doesn't do the trick?

**Comment by abuiles** [comment]
Probably you can remove moment from dependencies and add it via install ?

**Comment by jasonmit** [comment]
Moment is an npm dep as well, moment time zone is a bower dep and brings in moment with it.  I'll try and see about bringing moment time zone in as an npm dep as well

**Comment by abuiles** [comment]
cool, I'm experimenting in my own fork and doing this https://github.com/abuiles/ember-cli-moment-shim/commit/a332ae42236ca9a7fc71098eb2e7785f643994a0 works perfect for the scenario I'm tryng to cover. (maybe it might need to go in devDependencies) 

Also it looks like the `treeForApp` is not being called when doing `ember test`, I keep getting 

```
Error: Could not find module `ember-moment/computeds/moment` imported from `garaje/components/plan-ledger`
```

**Comment by abuiles** [comment]
oh, `treeForApp` is being called. Still trying to figure why is this issue appearing while in the browser it works fine.

**Comment by jasonmit** [comment]
> Error: Could not find module `ember-moment/computeds/moment` imported from `garaje/components/plan-ledger`

Can you post your project or reproduce this in an isolated app?

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-cli-moment-shim/commit/414d59310a8e9fda02f8530f37ae84791af38b5a

**Comment by abuiles** [comment]
@jasonmit ok, so the issue with the import seems to be only in my project, I didn't get the issue in  a clean project. thanks!

**Comment by abuiles** [comment]
@jasonmit 

> 414d593

Why don't you leave it in package.json? just add it to the package.json in the after install?

**Comment by abuiles** [comment]
the idea down the road is to kill bower, so that could be better too.

**Comment by jasonmit** [comment]
@abuiles because it's already being pulled in via bower as a dep of moment-timezone, so might as well use that instead of pulling it in twice once via bower and once via npm.

I can't use the moment-timezone package over npm because it does not provide `builds`, it just provides one dist which isn't optimal in the browser.
