### ISSUE TITLE
Fix breaking changes in FastBoot 1.0

### ISSUE THREAD

**Issue by simonihmig** [jasonmit/ember-cli-moment-shim#141]
The current `ember-cli-fastboot` releases (1.0.0-rc.1 and above) introduce breaking changes. These will most likely break your current FastBoot implementation.

See https://github.com/ember-fastboot/ember-cli-fastboot/issues/387 for more information and a guide on how to fix your addon. Also you may want to visit the `-fastboot` Slack channel to get help from other users.

*Note: this issue has been created automatically, by searching for certain patterns in your code. If you think this has been falsely created, feel free to close!*

**Comment by jasonmit** [comment]
This was fixed a few weeks back - are you noticing something not working?

Ref: https://github.com/jasonmit/ember-cli-moment-shim/commit/493b5ab2b281da45e5df96f5d69c1a84f26bcbab

**Comment by simonihmig** [comment]
> are you noticing something not working?

@jasonmit No, as written above the issue was created automatically to inform all addon authors of those breaking changes. In you case it was triggered by https://github.com/jasonmit/ember-cli-moment-shim/blob/master/index.js#L16. But it seems you support beta and rc versions, so this can be ignored then. Sorry for the false alarm! ;)
