### ISSUE TITLE
moment.tz is undefined

### ISSUE THREAD

**Issue by amk221** [jasonmit/ember-cli-moment-shim#142]
Might be having a silly 'moment' here, but with a fresh ember-cli project
and `ENV.moment.includeTimezone = 'all'` 

`moment.tz` === undefined

```
ember-cli: 2.14.0
node: 6.9.1
os: darwin x64
```

**Comment by jasonmit** [comment]
I spun up an new project with ember-cli@2.14.0 and could not replicate.  Can you push your fresh project anywhere?  Do you happen to have other addons installed?  If so, can you paste what they are.

![image](https://user-images.githubusercontent.com/3108309/28157025-f4da10d4-6769-11e7-8b82-8efafd36c8c5.png)

**Comment by amk221** [comment]
Yeh, it was my mistake. Thought it would be 😆

Sorry for your time!
