### ISSUE TITLE
`FastBoot is not defined` – Issues with lazy-loading engines and ember-cli-moment-shim

### ISSUE THREAD

**Issue by briangonzalez** [jasonmit/ember-cli-moment-shim#145]
We're attempting to use `ember-cli-moment-shim` in our _non-fastbooted_ ember app. We're encountering an error when we navigate to our lazy-loaded engine (see below).

I suspect [this line](https://github.com/jasonmit/ember-cli-moment-shim/blob/master/public/fastboot-moment-timezone.js#L3) is causing the issue, as `FastBoot` is not defined.

Any ideas?

<img width="508" alt="screen shot 2017-08-30 at 8 37 45 am" src="https://user-images.githubusercontent.com/659829/29882075-dba56358-8d60-11e7-9059-9f2471d1eb83.png">

**Comment by jasonmit** [comment]
@briangonzalez First time this is reported and it's used heavily through ember-moment.  I suspect Ember engines is doing something that I wasn't anticipating.  Can you replicate it with a dummy app?

If not, I have some ideas on how to remove `FastBoot.require`.  Will try that later on tonight if I don't hear back.

**Comment by majew7** [comment]
@jasonmit This issue was reproducible when building in 'production' environment mode.

    ember build --environment "production"

Context:
 - Ember Engine uses ember-cli-moment-shim
 - Build in 'production' env
 - Not using FastBoot

**Comment by jasonmit** [comment]
Thanks for the feedback @majew7, the issue occurs with and without lazy engines?

**Comment by jasonmit** [comment]
Before I version, can either of you verify this fixes the issue:
https://github.com/jasonmit/ember-cli-moment-shim/commit/591ae7a3c164df8023838d4f04e20c98583b555c

**Comment by majew7** [comment]
Yes, @jasonmit, I will verify in the next 24 hours.

**Comment by majew7** [comment]
It's working @jasonmit.  Retrieving from `"ember-cli-moment-shim": "^3.3.3"` things look good.

**Comment by majew7** [comment]
Hi @jasonmit,
While my local development test looked good with
`"ember-cli-moment-shim": "jasonmit/ember-cli-moment-shim.git#591ae7a",`
 I wanted to also verify in our QA environment.  I should know soon.

**Comment by jasonmit** [comment]
3.5.0 resolves this, thanks everyone

**Comment by majew7** [comment]
Thanks @jasonmit!  We are consuming the new 3.5.0 version.  Much appreciated.
