### ISSUE TITLE
Issue with new fastboot ember-engines support

### ISSUE THREAD

**Issue by mazondo** [jasonmit/ember-cli-moment-shim#154]
when working with the new fastboot support for ember-engines (https://github.com/ember-engines/ember-engines/pull/494) ember-cli-moment-shim is throwing the following error: `TypeError: Cannot set property 'compare' of undefined`

It looks like this is referring to here: https://github.com/jasonmit/ember-cli-moment-shim/blob/master/addon/index.js

I've been sleuthing through the trees, and I'm not sure I fully get how this library is being handled in Fastboot using the manifest generated files.  I see some PRs for engines, and others for fastboot, but anyone familiar with both together?

**Comment by Duder-onomy** [comment]
I am running into the same exact issue, and I am not using engines. 

What I have found is, 
this line: https://github.com/jasonmit/ember-cli-moment-shim/blob/master/addon/index.js#L17
Is trying to set `compare` on to moment and its prototype, however, moment is undefined. 
In that file, moment is imported from `./lib` which exports moment... but that export is undefined in fastboot land.  Using the node debugger, I can see that `self` in that file contains all kinds of good stuff.... just not moment....

![image](https://user-images.githubusercontent.com/1612785/35760607-38831a20-0836-11e8-92eb-6c5b6471fe33.png)

I will chime in again as I dig into this one.

**Comment by Duder-onomy** [comment]
@mazondo I figured out how to fix this, but I am still digging into WHY it is a problem. 
You MUST include `ember-moment` and `ember-cli-moment-shim` in the `package.json` of the parent app if you want it to work during fast boot. 

@jasonmit Do you know why we would need to include Moment in our parent apps package.json directly to get it working in fastboot? Seems like addons that use moment will be broken in fastboot.

**Comment by jasonmit** [comment]
> Do you know why we would need to include Moment in our parent apps package.json directly to get it working in fastboot?

Is this a case where you have an addon that is dependent on moment?

**Comment by jasonmit** [comment]
I have a pretty good sense of the issue (`Fastboot.require`), will try and figure out a solution soon.

For now, if you have an app that needs fastboot and have an addon that has a dep on moment/moment-timezone then add them as immediate deps to your app.

**Comment by Duder-onomy** [comment]
Thanks @jasonmit ! Yeah, I have an in-repo-addon that uses moment, but my main app does not. Putting that into the main apps package.json is fine with me for now.

**Comment by thec0keman** [comment]
Looking into this more...  (migrating our app that has engines to fastboot)

It looks like both the public and addon definitions of `lib/moment` are being evaluated in fastboot world, and the latter is taking precedence.  As a result, `self.moment` is meaningless.

Out of curiosity: what is the advantage of using the current public imports vs. moving the logic to the `./lib` file?

```
/* globals self */

let moment;

if (typeof FastBoot === 'undefined') {
  moment = self.moment;
} else {
  moment = FastBoot.require('moment');
}

export default moment;
```

That seems to work just fine, although that does not include the timezone support.
