### ISSUE TITLE
3.5.1 breaks build

### ISSUE THREAD

**Issue by mydea** [jasonmit/ember-cli-moment-shim#157]
After updating from 3.5.0 to 3.5.1, my build is not working anymore.

I get this error:

```
Build Error (Concat)

ENOENT: no such file or directory, open 'C:\...\tmp\source_map_concat-input_base_path-phKRngPs.tmp\vendor\moment-timezone\tz.js'
```

Dowgrading back to 3.5.0 fixes it for me.

I'm not entirely sure, I found this commit, which says "BREAKING": https://github.com/jasonmit/ember-cli-moment-shim/commit/63894b9ba0f47de857aa3ed78d8d10eb0f755a4b

But it was released as a patch version? Do I need to change anything?

I found this issue in a lazy loaded engine, on Ember 2.18.

**Comment by brianshano** [comment]
It also broke my build when trying to run ember in Ubuntu.
ember 2.9.1 
```jquery#3.3.1 bower_components/jquery
Unexpected token =
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Function.Addon.lookup (/home/ubuntu/project/node_modules/ember-cli/lib/models/addon.js:998:19)
    at /home/ubuntu/project/node_modules/ember-cli/lib/models/addons-factory.js:48:38
    at visit (/home/ubuntu/project/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
```


Reverting to 3.5.0 fixed it too

**Comment by Speennaker** [comment]
Hello! I have the same issue as @brianshano 

> Unexpected token =
09:11:51 SyntaxError: Unexpected token =
09:11:51     at exports.runInThisContext (vm.js:53:16)
09:11:51     at Module._compile (module.js:373:25)
09:11:51     at Object.Module._extensions..js (module.js:416:10)
09:11:51     at Module.load (module.js:343:32)
09:11:51     at Function.Module._load (module.js:300:12)
09:11:51     at Module.require (module.js:353:17)
09:11:51     at require (internal/module.js:12:17)
09:11:51     at Function.Addon.lookup (/opt/jenkins_work/workspace/Buzzkill_Master_Build/core/client/node_modules/ember-cli/lib/models/addon.js:889:19)
09:11:51     at /opt/jenkins_work/workspace/Buzzkill_Master_Build/core/client/node_modules/ember-cli/lib/models/addons-factory.js:47:38
09:11:51     at visit (/opt/jenkins_work/workspace/Buzzkill_Master_Build/core/client/node_modules/ember-cli/lib/utilities/DAG.js:23:3)

**Comment by jasonmit** [comment]
Will release another patch, apologies for that.

**Comment by jasonmit** [comment]
3.5.3 resolves this.  I'll reintroduce the breaking changes in the next major version bump.  For now, reverted all the breaking commits.
