### ISSUE TITLE
Remove deprecated exists-sync dependency

### ISSUE THREAD

**Issue by Bartheleway** [jasonmit/ember-cli-moment-shim#159]
Hi,

I'm getting the following warning in my console :
`warning ember-cli-moment-shim > exists-sync@0.0.4: Please replace with usage of fs.existsSync`

Does this dependency is still in use ?

**Comment by jasonmit** [comment]
Still used, feel free to submit a PR for it's removal.

**Comment by Bartheleway** [comment]
I have some troubles with the compilation because I'm using node 9. Do you think it would be an issue to enable version 9 for this project ?

**Comment by jasonmit** [comment]
@Bartheleway unclear what the issue is.  Can you post the logs you're seeing that indicate ember-cli-moment-shim is incompatible with Node 9?

The above log you provided is a warning and shouldn't break your build.

**Comment by Bartheleway** [comment]
Let me clarify then. I did try to make a PR but when I tried to compile this project to check everything was okay with my configuration (Node 9), the built was failing. I unfortunately don't remember what was the exact error.

I currently don't have access to my computer but I will try again soon and give you the error.

**Comment by Bartheleway** [comment]
I'm getting this error :
`error ember-cli-babel@6.0.0-beta.9: The engine "node" is incompatible with this module. Expected version "^4.5 || 6.* || 7.*".`

I think this might comes from at least ember-try and ember-disable-prototype-extensions but even if I remove these, I still get the error. Any ideas ? I will continue to try looking at package.json to see I found a way to make it work.

**Comment by Bartheleway** [comment]
I did my PR using `yarn --ignore-engines`. I hope this will not cause any trouble (this should not).

**Comment by jasonmit** [comment]
3.7.0 - thanks!
