### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by kle-dev** [jasonmit/ember-cli-moment-shim#161]
After updating Ember on latest version: 

I followed this tutorial: https://github.com/ember-cli/ember-cli/releases/tag/v3.1.2

I got: 

`broccoli-persistent-filter:Mapper: Expected Broccoli node, got undefined for inputNodes[0]`

caused by ember-cli-moment-shim.

**Comment by jasonmit** [comment]
Can you mention which version on moment shim you are using?

**Comment by jasonmit** [comment]
Can you also try 3.6.0 if 3.7.0 is causing this and report back

**Comment by kle-dev** [comment]
I tried 3.6.0 and the newest 3.7.0

**Comment by jasonmit** [comment]
Can you then try and reproduce it with a demo app?  Hard for me to fix if unable to reproduce

**Comment by kle-dev** [comment]
ember new projectname
ember install ember-cli-moment-shim
ember s

and then:
`broccoli-persistent-filter:Mapper: Expected Broccoli node, got undefined for inputNodes[0]`

**Comment by jasonmit** [comment]
`ember i ember-cli-moment-shim@3.6.0` does not have this issue, it's a bug that appeared in 3.7.0.  I'll look into fixing, for now target 3.6.0

**Comment by jasonmit** [comment]
3.7.1, thanks
