### ISSUE TITLE
QUEST - Make Ember CLI Moment Shim Optional

### ISSUE THREAD

**Issue by rtablada** [jasonmit/ember-cli-moment-shim#164]
Ember CLI Moment Shim was built as just that: a shim to be able to `import moment from 'moment';`.
It has served this purpose great but we are on the horizon of being able to just import moment without any extra fanfare or shim.
This quest serves as a place to list known community addons that have a hard dependency for `ember-cli-moment-shim` and a place to log progress of helping to remove this dependency.

---

Some strategies for making `ember-cli-moment-shim` optional for addons:

1. Move `ember-cli-moment-shim` from `dependencies` to `devDependencies`
2. Install `ember-cli-moment-shim` in the addon blueprint (ideally only installing shims for host apps that do not have `ember-auto-import` or packager)

---

Things to still figure out:

1. List of addons that are depending on `ember-cli-moment-shim` in `dependencies`
2. How to determine if a shim is needed
3. Timezone configuration without shim?
4. Does packager and `ember-auto-import` gracefully handle development/production imports?

**Comment by jasonmit** [comment]
I've made you collaborator if you want to carry the torch on this quest.  I'm in agreement that we should start leveraging the current shift to auto-import & the eventual packager hook(s).

**Comment by erichaus** [comment]
Is this needed anymore or better to just npm i moment?

**Comment by jasonmit** [comment]
@burritoIand not really unless you care about targeting specific locale & timezone data for payload size reasons.

**Comment by erichaus** [comment]
ok so I noticed that I had `moment`, `ember-moment`, and `ember-cli-moment-shim` in my project and thought I need to clean it up.. but ember-moment, which I use for a few template helpers it offers, includes moment AND ember-cli-moment-shim as dependencies of it's own!

I tried removing ember-cli-moment-shim and relying on my own `moment` dependency, but for some reason that breaks fastboot. Reinstall ember-cli-moment-shim fixed fastboot :/ So for the moment I'm going to leave it alone but hope to revisit soon.

**Comment by erichaus** [comment]
ended up replacing all momentness with dayjs and a few custom helpers :)

**Comment by maxhq** [comment]
I case anyone runs into the same problems as me:
When trying to replace *ember-cli-moment-shim* with *moment* while using *ember-cli-bootstrap-datetimepicker* there is a complaint from *bootstrap-datetimepicker*:
It can't find the global `moment` variable.

I solved it by adding this to *ember-cli-build.js*:
```javascript
app.import('node_modules/moment/moment.js', { prepend: true });
```
It did not work without the `prepend: true` and took me a long time to figure out.

**Comment by jrjohnson** [comment]
Success! This addon is no longer required and instructions for bundling moment, locales, and timezones can be found on the `ember-moment` README as of v10.
