### ISSUE TITLE
Advantages over ember-auto-import?

### ISSUE THREAD

**Issue by jacobq** [jasonmit/ember-cli-moment-shim#166]
I am currently using this shim in a project but am trying to migrate to using [`ember-auto-import`](https://github.com/ef4/ember-auto-import). Can you help me understand how this differs? For example, would this cause me to lose fastboot support and/or the ability to trim the locale data?

**Comment by jasonmit** [comment]
See: https://github.com/jasonmit/ember-cli-moment-shim/issues/164 for this discussion
