### ISSUE TITLE
Months translation missing for Russian locale

### ISSUE THREAD

**Issue by belgoros** [jasonmit/ember-cli-moment-shim#170]
I have weird behaviour when displaying a date picker for `Russian` locale (`ru`). 
I'm using [ember-pikaday](https://github.com/adopted-ember-addons/ember-pikaday) add-on and defined the initializer as it was [suggested](https://github.com/adopted-ember-addons/ember-pikaday#localization):
```
#app/initializers/setup-pikaday-i18n.js

import Ember from 'ember';
import moment from 'moment';

export default {
  name: 'setup-pikaday-i18n',
  initialize: function(application) {
    var i18n = Ember.Object.extend({
      months: moment.localeData()._months,
      weekdays: moment.localeData()._weekdays,
      weekdaysShort: moment.localeData()._weekdaysShort
    });

    application.register('pikaday-i18n:main', i18n, { singleton: true });
    application.inject('component:pikaday-input', 'i18n', 'pikaday-i18n:main');
  }
};
```
It works fine for all other languages but not for Russian.
The line `months: moment.localeData()._months` returns correctly the months
```
January,February,March,April,May,June,July,August,September,October,November,December
```
the same for translated versions of other languages but not for Russian where it sends `[Object object]`.

Here is how the failing display looks like:
<img width="318" alt="Screenshot 2019-04-09 at 16 43 29" src="https://user-images.githubusercontent.com/83579/55810643-38996400-5ae8-11e9-81c3-7c9eeaefeda7.png">

I also enabled all the locales in `config/environment.js`: 
```
...
moment: {
      includeLocales: true
    }
```

I grab the User locale in `application.js` route as follows:
````
#routes/application.js

export default Route.extend(ApplicationRouteMixin, {
  currentUser: service(),
  intl: service(),

  beforeModel() {
    let locale = this.figureOutLocale();
    this.intl.setLocale(locale);
    moment.locale(locale);
    console.log('months: ' + moment.localeData()._months);
    
    return this._loadCurrentUser();
  },

  sessionAuthenticated() {
    this._super(...arguments);
    this._loadCurrentUser();
  },

  _loadCurrentUser() {
    return this.get('currentUser').loadCurrentUser().catch(() => this.get('session').invalidate());
  },

  figureOutLocale() {
    let locale = this.calculateLocale(this.intl.get('locales'));
    return locale;
  },

  calculateLocale(locales) {
    const userLanguage = navigator.languages[0] || navigator.language || navigator.userLanguage;    
    let matchedLanguage = userLanguage.match(/\w{2}/)[0].toLowerCase();

    return  locales.includes(matchedLanguage) ? matchedLanguage : 'en';
  }
});
```

What's wrong with that? Thank you.

**Comment by belgoros** [comment]
It seems like the problem comes from the way the `months` variable is [defined](https://github.com/moment/moment/blob/develop/locale/ru.js#L37) in the corresponding [ru.js](https://github.com/moment/moment/blob/develop/locale/ru.js) file:
```
...
months : {
            format: 'января_февраля_марта_апреля_мая_июня_июля_августа_сентября_октября_ноября_декабря'.split('_'),
            standalone: 'январь_февраль_март_апрель_май_июнь_июль_август_сентябрь_октябрь_ноябрь_декабрь'.split('_')
        },
...
````
it is a Hash and not String as in [fr.js](https://github.com/moment/moment/blob/develop/locale/fr.js#L12) translation, for example.
It means that we should access it by the `standalone` key:
```
months: moment.localeData()._months['standalone'],
// instead of a classic one
months: moment.localeData()._months,
```
Is it sooner a [moment.js](https://github.com/moment/moment) issue ?

**Comment by ashsearle** [comment]
Use `moment.localeData().months()` instead.

**Comment by belgoros** [comment]
@ashsearle Thank you for your response. I modified and used `month()` instead in the pikaday initiaizer:
```
import Ember from 'ember';
import moment from 'moment';

export default {
  name: 'setup-pikaday-i18n',
  initialize: function(application) {
    var i18n = Ember.Object.extend({
      months: moment.localeData().months(),
      weekdays: moment.localeData()._weekdays,
      weekdaysShort: moment.localeData()._weekdaysShort
    });

    application.register('pikaday-i18n:main', i18n, { singleton: true });
    application.inject('component:pikaday-input', 'i18n', 'pikaday-i18n:main');
  }
};
```
but it still displays `undefined` for months in the datepicker popup.
Even changing for:
```
months: moment.localeData()._months['standalone'],
```
does not solve the problem either. It concerns only the **Russian** locale, all the others (French, English, Portuguese) work fine 😢

**Comment by belgoros** [comment]
`moment.js` seems to [manage](https://github.com/moment/moment/blob/develop/moment.js#L929) the case when `months` are not an Array:
```
function localeMonths (m, format) {
        if (!m) {
            return isArray(this._months) ? this._months :
                this._months['standalone'];
        }
...
```

**Comment by ashsearle** [comment]
@belgoros I can only comment on the moment stuff: use [the localeData methods](https://momentjs.com/docs/#/i18n/locale-data/) instead of accessing private properties like `_months`, and you should end up with consistent data structures for every locale (e.g. arrays for months.)

**Comment by belgoros** [comment]
@ashsearle , ok, I think it is sooner a [ember-pikaday](https://github.com/adopted-ember-addons/ember-pikaday) issue. I'll close this one and open a new one at `ember-pikaday` repo. Thank you.
