### ISSUE TITLE
Should moment-timezone be huge?

### ISSUE THREAD

**Issue by RobbieTheWagner** [jasonmit/ember-cli-moment-shim#181]
It seems like moment-timezone is almost double the size of Ember, which is surprising.

<img width="562" alt="Screen Shot 2020-02-20 at 9 22 46 AM" src="https://user-images.githubusercontent.com/2640861/74944577-41bfb680-53c4-11ea-8894-32a00b2a618c.png">

**Comment by jasonmit** [comment]
@rwwagner90 seems way off.

https://momentjs.com/timezone/ includes the sizes for comparison (12kb w/ data)

**Comment by RobbieTheWagner** [comment]
Something is off then. This is the size when including all timezeones it seems.

**Comment by jasonmit** [comment]
On second thought - your screenshot isn't including gzipped numbers.  It should be about 20-30kb gzipped as the moment-timezone site advertises.  I also verified resource size vs transfer size on moment's own site serving up moment-timezone w/ data:

![image](https://user-images.githubusercontent.com/3108309/80319831-8b16f280-87c7-11ea-969b-067d73f69edb.png)

Raw file sizes of timezone match the numbers you're seeing.
![image](https://user-images.githubusercontent.com/3108309/80319762-06c46f80-87c7-11ea-8021-a930850da564.png)
