### ISSUE TITLE
can you increment major instead of minor for 3.8.0 release

### ISSUE THREAD

**Issue by nagasai-praveen** [jasonmit/ember-cli-moment-shim#186]
since there is a babel version change in v3.8.0 instead of minor increment can you do major increment.

the problem I am facing is I am using `ember-power-calendar` which is having dependency of `ember-cli-moment-shim` i am using babel 5 but due to your recent release and increment of `babel` version it is causing problem in my addon.

or else can you guide me how to lock `ember-cli-moment-shim` dependency

**Comment by jrjohnson** [comment]
@nagasai-praveen can you tell us a bit more about how this is breaking for your app? I'm fairly certain that ember-cli does some magic internally to ensure that addons and apps can have very different versions of `ember-cli-babel` without causing any breaking issues.

**Comment by nagasai-praveen** [comment]
Even in my package.json i tried locking `ember-cli-moment-shim`

so below is my addon package.json 

`{ "name": "ember-dynamic-form", "version": "1.12.0", "description": "The default blueprint for ember-cli addons.", "directories": { "doc": "doc", "test": "tests" }, "scripts": { "build": "ember build", "start": "ember server", "test": "ember try:each", "test-server": "COVERAGE=TRUE ember test --server" }, "repository": "", "engines": { "node": ">= 0.10.0" }, "author": "", "license": "MIT", "devDependencies": { "active-model-adapter": "2.1.1", "broccoli-asset-rev": "^2.4.2", "ember-ajax": "^2.0.1", "ember-cli": "2.8.0", "ember-cli-app-version": "^1.0.0", "ember-cli-code-coverage": "0.3.12", "ember-cli-dependency-checker": "^1.2.0", "ember-cli-deprecation-workflow": "0.2.5", "ember-cli-eslint": "4.1.0", "ember-cli-fake-server": "0.4.0", "ember-cli-inject-live-reload": "^1.4.0", "ember-cli-mirage": "0.2.5", **"ember-cli-moment-shim": "~3.0.0",** "ember-cli-page-object": "1.11.0", "ember-cli-qunit": "^2.1.0", "ember-cli-release": "0.2.9", "ember-cli-sri": "^2.1.0", "ember-cli-stack-trace-limit": "0.0.1", "ember-cli-template-lint": "0.7.0", "ember-cli-test-loader": "^1.1.0", "ember-cli-uglify": "^1.2.0", "ember-concurrency": "0.8.10", "ember-cp-validations": "3.1.4", "ember-data": "2.8.1", "ember-disable-prototype-extensions": "^1.1.0", "ember-exam": "1.0.0", "ember-export-application-global": "^1.0.5", "ember-load-initializers": "^0.5.1", "ember-moment": "7.1.0", "ember-native-dom-helpers": "0.5.2", "ember-resolver": "^2.0.3", "ember-test-selectors": "^0.3.6", "ember-truth-helpers": "1.3.0", "ember-try": "1.1.0", "ember-welcome-page": "^1.0.1", "eslint-plugin-ember": "^3.6.2", "loader.js": "^4.0.1", "mirage": "0.0.6" }, "keywords": [ "ember-addon", "dynamic-form", "ember-form" ], "dependencies": { "ember-cli-babel": "^5.1.6", "ember-cli-htmlbars": "^1.0.3", "ember-cli-htmlbars-inline-precompile": "^0.3.1", "ember-power-calendar": "0.7.1", "ember-power-calendar-moment": "0.1.4", "ember-form-for": "v2.0.0-beta.1", "ember-power-select": "1.7.0", "ember-power-select-with-create": "0.4.2" }, "ember-addon": { "configPath": "tests/dummy/config" } }`


But my app is failing to start
![image](https://user-images.githubusercontent.com/59957573/87660819-4aeb5e80-c77d-11ea-859f-cc9be6a7d34d.png)
