### ISSUE TITLE
includeLocales: true stopped working in 3.8.0

### ISSUE THREAD

**Issue by mydea** [jasonmit/ember-cli-moment-shim#187]
After updating from 3.5.0 to 3.8.0, `includeLocales: true` stopped working with the error:

```
ENOENT: no such file or directory, open '/tmp/broccoli-7755BBEmsOOPNspH/out-297-broccoli_debug_debug_2_vendor_js/vendor/moment/moment-with-locales.js'
```

Removing the line makes the build work again, however then it does not include all locales. It works if I manually specify locales.

This happens in an addon's dummy app.

**Comment by jasonmit** [comment]
@mydea if at all possible, I'd move away from using this addon.  Since you're bundling all locales it doesn't seem like you need any of it's capabilities.

It doesn't add much value anymore now that bundling libs is effortless with ember-auto-import.

**Comment by mydea** [comment]
Yeah, in that case it didn't really matter, as I could specify the locales, and it's just for an addon's dummy app. However, it was rather unexpected and took me some time to find the cause of my sudden build failures :)

**Comment by rreckonerr** [comment]
Got this same error upgrading from 3.7.1

**Comment by mehulkar** [comment]
cc @jrjohnson. Issue is from #184. Just need to change the import path: 

https://github.com/jasonmit/ember-cli-moment-shim/pull/184/files#r564138289

**Comment by jrjohnson** [comment]
Locales can now be bundled without this addenda following the instructions at `ember-moment`.
