### ISSUE TITLE
Moment.js is shutting down

### ISSUE THREAD

**Issue by kriswill** [jasonmit/ember-cli-moment-shim#188]
Now that moment.js is no longer going to be updated, what alternatives should we seek for this Addon?

See: https://momentjs.com/docs/#/-project-status/

**Comment by jasonmit** [comment]
There's luxon, dayjs, native Intl.DateTimeFormat APIs, etc.  As for a replacement to this addon, I don't believe it's been that useful since ember-auto-import made bundling external libs significantly easier than what was there prior.

Loading something like dayjs should now be as simple as:

```
ember install ember-auto-import
npm install dayjs
```

```
import dayjs from 'dayjs';
```

**Comment by jasonmit** [comment]
Closing as it's now reflected into the README
