### ISSUE TITLE
TypeError: Cannot redefine property: name

### ISSUE THREAD

**Issue by fsmanuel** [jasonmit/ember-cli-moment-shim#189]
Hey @jasonmit I used ember-cli-moment-shim for years and love it. In a current project I run into the problem that old browsers for example Chrome Mobile WebView 39 throw a `TypeError: Cannot redefine property: name` here: https://github.com/jasonmit/ember-cli-moment-shim/blob/master/addon/lib.js#L16

I'm not familiar with the loader.js and what could be a solution to fix this problem.
@rwjblue can you help?

Here is the Sentry stack trace:

<img width="625" alt="cannot_redefine_property" src="https://user-images.githubusercontent.com/54812/106020024-97680d00-60c3-11eb-8f59-2f5d832bbf36.png">

**Comment by jasonmit** [comment]
I'd recommend migrating away from this addon as it's no longer actively maintained.  Moment itself has also been put in legacy mode: https://sebastiandedeyne.com/moment-js-thank-you-for-your-service/

**Comment by fsmanuel** [comment]
@jasonmit thanks for the recommendation. I'll see if I can do the migration.
