### ISSUE TITLE
NPM vulnerability with moment/2.29.3

### ISSUE THREAD

**Issue by amit199309** [jasonmit/ember-cli-moment-shim#193]
Hi Team,

As we are internally using moment with version 2.29.3 [ember-cli-moment-shim](https://github.com/jasonmit/ember-cli-moment-shim) that causing npm vulnerability. This can we fixed if we increase moment dependency version from 2.29.3 to 2.29.4 ( latest version ). Please check and suggest.

Thank you

**Comment by jrjohnson** [comment]
You should do so in your app, I don't think any change is required here. If I'm not understanding your question please re-open and add more details about what needs to change. 

As an aside you can also drop this add-on entirely and follow the instructions at https://github.com/adopted-ember-addons/ember-moment#using-momentjs-in-ember-apps--addons to include moment in your ember app.
