### ISSUE TITLE
Ember-cli upgrade results in Cannot read property 'momentPath' of undefined

### ISSUE THREAD

**Issue by coladarci** [jasonmit/ember-cli-moment-shim#20]
Just upgraded ember-cli to the latest and my project is failing w/

```
version: 1.13.12
Cannot read property 'momentPath' of undefined
TypeError: Cannot read property 'momentPath' of undefined
    at Class.module.exports.treeForVendor ([MY PROJECT PATH]/node_modules/ember-cli-moment-shim/index.js:93:34)
```

The line that is failing in your index.js is:

```

  treeForVendor: function(vendorTree) {
    var trees = [];
    var options = this.options;

    if (vendorTree) {
      trees.push(vendorTree);
    }

    trees.push(new Funnel(options.momentPath, {
      destDir: 'moment',
      include: [new RegExp(/\.js$/)],
      exclude: ['tests', 'ender', 'package'].map(function(key) {
        return new RegExp(key + '\.js$');
      })
    }));
```

Any ideas?

**Comment by jasonmit** [comment]
I'm unable to reproduce this on a fresh ember-cli 1.13.12 app.  Can you provide more details and/or share a sample project with the issue isolated.

Are you using this with ember-moment or another addon?  The only thing I can think of is options is colliding with something else.  Can you try ember-cli-moment-shim@0.7.1

If that still doesn't work, I'll need you to put together something that can replicate the issue.

**Comment by coladarci** [comment]
Hey Jason - apologies for the firedrill - as you may have suspected, this is due to a bad ember-cli upgrade. I'm not 100% sure what was wrong, but my package.json must have had some bad values since I was experiencing this issue inside an Addon, yet the package.json was upgraded as if it was NOT an addon. Closing...

**Comment by jasonmit** [comment]
It happens, thanks for the quick follow up.
