### ISSUE TITLE
Fastboot support

### ISSUE THREAD

**Issue by rlivsey** [jasonmit/ember-cli-moment-shim#24]
Currently if you run under Fastboot and have moment-timezone enabled, an error is thrown on build because moment-timezone notices it's running under NPM (`require` is present) and attempts to require moment, which fails because obviously neither library is present in `node_modules`:

```
Built project successfully. Stored in "fastboot-dist".
Installing FastBoot npm dependencies
Could not find module `moment` imported from `(require)`
Error: Could not find module `moment` imported from `(require)`
    at missingModule (/Users/rlivsey/Development/experiments/fastboot-test/fastboot-dist/assets/vendor/loader/loader.js:164:1)
    at findModule (/Users/rlivsey/Development/experiments/fastboot-test/fastboot-dist/assets/vendor/loader/loader.js:179:1)
    at requireModule (/Users/rlivsey/Development/experiments/fastboot-test/fastboot-dist/assets/vendor/loader/loader.js:168:1)
    at /Users/rlivsey/Development/experiments/fastboot-test/fastboot-dist/assets/vendor/moment-timezone/tz.js:6:1
    at /Users/rlivsey/Development/experiments/fastboot-test/fastboot-dist/assets/vendor/moment-timezone/tz.js:6:1
```

I wonder if instead of using Bower, this addon should instead use NPM for the moment and moment-timezone dependencies and then it might work for both normal and Fastboot operation?

I should have some time this week to spike on this if you think this is a valid direction to go in, or if you have any other ideas for how best to get Fastboot support working.

**Comment by jasonmit** [comment]
1.0.0 is using npm packages and not bower.  As for fastboot support, I've been waiting on documentation to best support it.  If you want to take a shot at it, I'll be happy to review.

**Comment by rlivsey** [comment]
RE NPM - awesome, I hadn't spotted that change. I'll take a stab at Fastboot support in the next day or two and send a PR asap.

**Comment by jasonmit** [comment]
Looking forward, thanks :+1:

**Comment by jasonmit** [comment]
I spent a little time looking at this, and it looks like the require in moment-time/moment-timezone-with-data.js invokes the loader.js's require.

We could do two things, play around with https://github.com/ember-cli/loader.js#no-conflict or mutate the javascript to knock out `module.exports = factory(require('moment')); // Node` forcing it to use the `moment` global.

There may be other options.

**Comment by jasonmit** [comment]
Thanks again, super awesome.  Versioned as 1.1.0
