### ISSUE TITLE
Cannot overwrite `moment.now` from tests

### ISSUE THREAD

**Issue by SaladFork** [jasonmit/ember-cli-moment-shim#31]
In my application I have to group items with dates into buckets "Today", "Tomorrow", "Next Week", etc.. While writing tests for this functionality, I realized the tests would fail if today was on a boundary. For example, given the week starts Monday as per `isoWeek`, running the tests on Sunday would put an item with tomorrow's date into "Next Week" rather than "Tomorrow", causing the tests that look for "Tomorrow" to fail.

The way I've solved this in other apps that use moment is to overwrite [`moment.now`](http://momentjs.com/docs/#/customization/now/) to set "today" to a known date for various tests. However, with `ember-moment` (which uses this shim), it seems this doesn't work.

I've created an [example app](https://github.com/SaladFork/ember-moment-now-issue) to demonstrate the issue (note the [failing Travis tests](https://travis-ci.org/SaladFork/ember-moment-now-issue/builds/131208456)).

Is this something fixable? Is there a recommended workaround?

**Comment by jasonmit** [comment]
This is an ember-moment issue where `now` helper returns `new Date` and not `moment.now`

https://github.com/stefanpenner/ember-moment/pull/175

Will resolve this, will version as part of 7.0.0-beta.2
