### ISSUE TITLE
Use import polyfill?

### ISSUE THREAD

**Issue by elwayman02** [jasonmit/ember-cli-moment-shim#32]
https://github.com/ember-cli/ember-cli-import-polyfill

Right now ember-cli-moment-shim can handle being nested one level deep, thanks to [this fix](https://github.com/jasonmit/ember-cli-moment-shim/blob/master/index.js#L20). However, nesting any further will cause more problems. Perhaps you can use this backwards-compatible polyfill to allow it to be nested at any level?

**Comment by jasonmit** [comment]
I'm in favor, feel free to submit a pr

**Comment by jasonmit** [comment]
I'll likely end up reverting it: https://github.com/tomdale/ember-network/pull/7#issuecomment-222508610
