### ISSUE TITLE
Overwriting `moment.now` doesn't seem to work

### ISSUE THREAD

**Issue by adamreisnz** [jasonmit/ember-cli-moment-shim#41]
I am trying to overwrite `moment.now` function to use a server provided timestamps as per the [docs](http://momentjs.com/docs/#/customization/now/), however, it doesn't seem to work with `ember-cli-moment-shim`.

Is there anything different I need to do to get this to work with `ember-cli-moment-shim`?

**Comment by adamreisnz** [comment]
Current only work around I found is to directly access the global `moment` object itself, by omitting `import moment from 'moment'` with a `/* jshint -W117 */` warning supressor in place.

**Comment by jasonmit** [comment]
@adambuczynski yeah, this makes sense because ember-cli-moment-shim returns an EmberObject so changing it's reference of now to point to a different function won't impact the moment global.  I'm guessing then you're relying on some code that references the global instead of ember-cli-moment-shim?

**Comment by adamreisnz** [comment]
@jasonmit Yes I thought it would be something like that.

If you have a look at the link that I posted to the docs:

http://momentjs.com/docs/#/customization/now/

That feature is something that our application relies on -- we need to be able to override the `.now` function in order to feed a server time offset into moment.

Any way this can be achieved via the EmberObject moment object somehow?

**Comment by jasonmit** [comment]
I have a PR opened that should resolve this, will merge shortly.

https://github.com/jasonmit/ember-cli-moment-shim/issues/42

**Comment by adamreisnz** [comment]
Thank you, I will check if this resolved it later on.

**Comment by adamreisnz** [comment]
Can you release a new npm version with this patch included?

**Comment by jasonmit** [comment]
Versioned as 2.0.0

**Comment by adamreisnz** [comment]
Seems to be working now, thanks!

**Comment by adamreisnz** [comment]
Hi @jasonmit , I'm still running into issues with overwriting `moment.now`.

In various places of our application, it now triggers a "long running script" warning in both Firefox and IE. Chrome seems to be unaffected. The problem is created by simply overwriting `moment.now` with the following:

``` js
let offset = 0;
moment.now = function() {
  return Date.now() + offset;
};
```

Any thoughts as to what could be happening?
It happens both with importing the moment shim or just by extending the global object.

**Comment by adamreisnz** [comment]
It seemed the issue was with the way the offset was calculated. For some reasons it caused the scripts to hang. Have refactored it and now no longer seems to be an issue.

**Comment by jasonmit** [comment]
Nice, hopefully not a bug on my end.  Let me know if it resurfaces
