### ISSUE TITLE
Add FastBoot test support

### ISSUE THREAD

**Issue by jasonmit** [jasonmit/ember-cli-moment-shim#79]
Fastboot test support is in its infancy, but some exploring and if the path forward is clear enough.. then implement fastboot test support.

**Comment by kellyselden** [comment]
I've been working in this space recently. https://github.com/kellyselden/ember-data-fetch-support/pull/12 may get you almost all the way.

**Comment by jasonmit** [comment]
Excellent, I'll use this as a reference.  I'll try to work on this soon.
