### ISSUE TITLE
Ember.computed.sort not working since 3.0.0

### ISSUE THREAD

**Issue by ilucin** [jasonmit/ember-cli-moment-shim#97]
It can't sort arrays of moment objects because they are not instances of Ember.Comparable any more. Failing test provided in PR #96

**Comment by jasonmit** [comment]
Yeah, that's something I was apprehensive about continuing support in 3.0.0.  I naively thought the presence of `compare` off the prototype was enough for `Ember.computed.sort`.

The reason for the change was it made reassignments & comparisons flakey, maintaining a list of moment methods that return moment objects and wrapping them will not scale as changes go upstream into moment.

While you no longer can rely on the default `Ember.Comparable` behavior with `Ember.computed.sort`, you can provide a sorting function as the second argument of `Ember.computed.sort`.

```js
Ember.computed.sort(dateContainers, function(a, b) {
  return moment.compare(a.date, b.date);
})
```

The above will work in 3.0.1.  That said, I'd also be opened to including a computed property macro to abstract the boilerplate away.  That might look something like:

```js
/* should probably go upstream into ember-moment */
import { computedSort } from 'ember-moment';

const ObjClass = Ember.Object.extend({
  datesSortParam: ['date:asc'],
  sortedDateContainers: computedSort('dateContainers', 'datesSortParam')
});

const obj = ObjClass.create({
  dateContainers: Ember.A([
    { date: moment(20000) },
    { date: moment(0) },
    { date: moment(10000) }
  ])
});
```
